# Generated by Django 4.2.5 on 2023-10-07 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("uploader", "0001_initial"),
        ("amigosjvll", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="foto",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="uploader.image",
            ),
        ),
        migrations.AlterField(
            model_name="animal",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
