# Generated by Django 4.2.4 on 2023-08-14 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("amigosjvll", "0005_animal"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="preco",
            new_name="idade",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="isbn",
        ),
        migrations.AddField(
            model_name="animal",
            name="cor",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animais",
                to="amigosjvll.cor",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animal",
            name="especie",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animais",
                to="amigosjvll.especie",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animal",
            name="raca",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="animais",
                to="amigosjvll.raca",
            ),
            preserve_default=False,
        ),
    ]
