# Generated by Django 4.2.4 on 2023-08-14 13:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amigosjvll", "0006_rename_preco_animal_idade_remove_animal_isbn_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Apelido",
        ),
        migrations.RemoveField(
            model_name="animal",
            name="quantidade",
        ),
    ]
