# Generated by Django 4.2.4 on 2023-08-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amigosjvll", "0007_delete_apelido_remove_animal_quantidade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
