# Generated by Django 4.2.4 on 2023-08-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amigosjvll", "0008_alter_animal_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="imagem",
            field=models.CharField(
                default="https://scontent.ffln5-1.fna.fbcdn.net/v/t39.30808-6/340740165_169432112307756_6623547955058731944_n.jpg?stp=cp6_dst-jpg_s600x600&_nc_cat=109&ccb=1-7&_nc_sid=5cd70e&_nc_ohc=UY7hwyZmz1cAX-BKYiB&_nc_ht=scontent.ffln5-1.fna&oh=00_AfCxiNYIjh-JqJ3nZMLaOPSUe3FNTu_p486d7MH4qQuGuA&oe=643B612F",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
