# Generated by Django 4.2.4 on 2023-08-27 22:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("amigosjvll", "0011_rename_foto_animal_imagem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="animal",
            old_name="imagem",
            new_name="foto",
        ),
    ]
