# Generated by Django 4.2.5 on 2023-10-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amigosjvll", "0013_animal_descricao"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animal",
            name="descricao",
            field=models.CharField(max_length=500),
        ),
    ]
